import type { ParkExperience } from "../../domain/park/park-experience.js";

export const PARK_EXPERIENCE_CATALOG: readonly ParkExperience[] = [
  {
    parkId: "gangseo",
    summary: "습지 생태와 가족 피크닉을 함께 즐기기 좋은 서쪽 공원",
    highlights: ["강서습지생태공원 자연관찰로", "가족피크닉장", "방화대교 인근 인공암벽장"],
    cautions: ["도심 중심부에서 이동시간이 길 수 있어요"],
    signatureTags: ["nature", "picnic", "family"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/675.do?mid=482",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "gwangnaru",
    summary: "자전거·드론·갈대 경관처럼 야외 활동 선택지가 많은 공원",
    highlights: ["BMX와 자전거트랙이 있는 자전거공원", "한강드론장", "광진교8번가 전망쉼터"],
    cautions: ["상수원보호구역이라 수상 레저 활동이 제한돼요"],
    signatureTags: ["cycling", "sports", "nature"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/645.do?mid=429",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "nanji",
    summary: "캠핑·자전거·생태 공간을 한 번에 즐길 수 있는 여유로운 공원",
    highlights: ["난지캠핑장", "BMX·MTB 체험이 가능한 자전거공원", "거울분수와 생태습지원"],
    cautions: ["캠핑장은 별도 예약이 필요해요", "일부 물놀이 시설은 계절 운영이에요"],
    signatureTags: ["nature", "cycling", "family", "fountain"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/672.do?mid=478",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "ttukseom",
    summary: "수상 스포츠와 문화·운동시설이 모여 있는 활기찬 공원",
    highlights: ["윈드서핑 등 수상 스포츠", "뚝섬자벌레 문화공간", "음악분수와 인공암벽장"],
    cautions: ["대표 시설은 운영 시기와 이용 조건을 확인해야 해요"],
    signatureTags: ["water_leisure", "culture", "sports", "fountain"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/654.do?mid=449",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "mangwon",
    summary: "탁 트인 잔디와 노을, 이색 전시를 함께 보기 좋은 공원",
    highlights: ["시야가 넓은 잔디밭", "퇴역 군함을 활용한 서울함공원", "망원초록길과 망원정"],
    cautions: ["서울함공원은 별도 운영시간을 확인해야 해요"],
    signatureTags: ["picnic", "culture", "nature"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/666.do?mid=468",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "banpo",
    summary: "야경과 분수, 세빛섬을 중심으로 볼거리가 풍부한 공원",
    highlights: ["달빛무지개분수", "세빛섬 야경과 편의시설", "서래섬 산책과 계절 꽃"],
    cautions: ["무지개분수는 4~10월 중심의 계절 운영이에요", "행사일에는 혼잡이 커질 수 있어요"],
    signatureTags: ["fountain", "culture", "events"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/663.do?mid=463",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "yanghwa",
    summary: "넓은 잔디와 탁 트인 전망 속에서 차분하게 쉬기 좋은 공원",
    highlights: ["넓게 조성된 잔디밭", "선유교 아래 장미길", "여름철 양화물놀이장"],
    cautions: ["장미와 물놀이장은 계절에 따라 경험이 달라져요"],
    signatureTags: ["picnic", "nature", "family"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/678.do?mid=486",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "yeouido",
    summary: "접근성이 좋고 넓은 광장과 행사·공연을 함께 즐기기 좋은 대표 공원",
    highlights: ["여의도 물빛광장", "물빛무대와 다양한 행사", "너른들판·잔디마당과 샛강생태공원"],
    cautions: ["대형 행사일에는 도착 시점 혼잡 확인이 특히 중요해요", "분수는 계절 운영이에요"],
    signatureTags: ["picnic", "events", "fountain", "nature"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/669.do?mid=473",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "ichon",
    summary: "자연학습과 운동, 노들섬 문화공간을 함께 둘러보기 좋은 공원",
    highlights: ["노들섬 공연·전시와 잔디마당", "자연학습장", "인라인롤러스케이트장"],
    cautions: ["노들섬은 공원 내 만남 지점과 거리가 있을 수 있어요"],
    signatureTags: ["culture", "nature", "sports"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/660.do?mid=458",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "jamsil",
    summary: "자연형 물놀이와 생태 관찰을 가족 단위로 즐기기 좋은 공원",
    highlights: ["자연형 물놀이장", "잠실 물고기길", "자연학습장과 잔디쉼터"],
    cautions: ["물놀이 시설은 계절·시간별 운영 상태를 확인해야 해요"],
    signatureTags: ["family", "nature", "water_leisure"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/651.do?mid=444",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
  {
    parkId: "jamwon",
    summary: "자전거와 생활체육을 중심으로 강변 활동을 즐기기 좋은 공원",
    highlights: ["5.4km 자전거 코스", "축구·농구·테니스 등 체육시설", "계절별 수영장·눈썰매장"],
    cautions: ["수영장과 눈썰매장은 계절별 운영 여부를 확인해야 해요"],
    signatureTags: ["cycling", "sports", "family"],
    sourceUrl: "https://hangang.seoul.go.kr/www/contents/657.do?mid=454",
    verifiedAt: "2026-08-12",
    verificationStatus: "official_web_confirmed",
  },
] as const;

export function parkExperienceFor(parkId: string): ParkExperience {
  const experience = PARK_EXPERIENCE_CATALOG.find((item) => item.parkId === parkId);
  if (!experience) throw new Error(`park_experience_missing:${parkId}`);
  return experience;
}
